value_of_pi: value_of_pi.c common.h
	gcc -fopenmp value_of_pi.c -o value_of_pi
	./value_of_pi
	rm ./value_of_pi

array_proc: array_proc.c common.h
	gcc -fopenmp array_proc.c -o array_proc
	./array_proc
	rm ./array_proc

heat_calc: heat_calc.c common.h
	gcc -fopenmp heat_calc.c -o heat_calc
	./heat_calc
	rm ./heat_calc